### ISSUE TITLE
Questions about Tile Cropping

### ISSUE THREAD

**Issue by Breeze-Zero** [sagizty/BigModel#3]
Hello @sagizty , I just got into contact with pathology slices, thanks to your Tile Cropping code for making it easy for me to complete Cropping, but as I explore, I find that the Cropping method proposed by the older code base CLAM seems to save more space (which will reduce the burden of less storage space for us students). I would like to know what else is different or how your approach improves over CLAM's.

**Comment by sagizty** [comment]
Hi thanks for your interest in this repo,
In term of reducing the storage, I guess the mpp is the reason, with more fine mpp(0.5 vs 1.0), we preserve more tiles, so we take more space than CLAM. 
let's discuss more if you are into it. also we welcome you to use and contribute to this open source project.
